//
// Generated by JTB 1.3.3
//

package lang.visitor;
import lang.syntaxtree.*;
import java.util.*;

/**
 * All GJ List Visitors with no argument must implement this interface.
 */

public interface GJListVisitor<R,A> {

   public R visit(Node n, A argu);
}

