//
// Generated by JTB 1.3.3
//

package lang.visitor;
import lang.syntaxtree.*;
import java.util.*;

/**
 * All GJ No Argu List Visitors with no argument must implement this interface.
 */

public interface GJNoArguListVisitor<R> {

   public R visit(Node n);
}

