//
// Generated by JTB 1.3.3
//

package lang.visitor;
import lang.syntaxtree.*;
import java.util.*;

/**
 * All GJVoid List Visitors with no argument must implement this interface.
 */

public interface GJVoidListVisitor<A> {

   public void visit(Node n, A argu);
}

