//
// Generated by JTB 1.3.3
//

package lang.visitor;
import lang.syntaxtree.*;
import java.util.*;

/**
 * All List Visitors with no argument must implement this interface.
 */

public interface ListVisitor {

   public void visit(Node n);
}

