//
// Generated by JTB 1.3.3
//

package lang.syntaxtree;

import java.util.*;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(lang.visitor.Visitor v);
   public <R,A> R accept(lang.visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(lang.visitor.GJNoArguVisitor<R> v);
   public <A> void accept(lang.visitor.GJVoidVisitor<A> v, A argu);
   // It is the responsibility of each implementing class to call
   // setParent() on each of its child Nodes.
   public void setParent(Node n);
   public Node getParent();

   // ListVisitor's and subNodes methods.
   public void accept(lang.visitor.ListVisitor v);
   public <R,A> R accept(lang.visitor.GJListVisitor<R,A> v, A argu);
   public <R> R accept(lang.visitor.GJNoArguListVisitor<R> v);
   public <A> void accept(lang.visitor.GJVoidListVisitor<A> v, A argu);
   public void setSubNodes(ArrayList<Node> n);
   public ArrayList<Node> getSubNodes();
}

