//
// Generated by JTB 1.3.3
//

package lang.syntaxtree;

import java.util.*;

/**
 * Represents a grammar choice, e.g. ( A | B )
 */
public class NodeChoice implements Node {
   public NodeChoice(Node node) {
      this(node, -1);
   }

   public NodeChoice(Node node, int whichChoice) {
      choice = node;
      choice.setParent(this);
      subNodes.add(node);
      which = whichChoice;
   }

   public void accept(lang.visitor.Visitor v) {
      choice.accept(v);
   }
   public <R,A> R accept(lang.visitor.GJVisitor<R,A> v, A argu) {
      return choice.accept(v,argu);
   }
   public <R> R accept(lang.visitor.GJNoArguVisitor<R> v) {
      return choice.accept(v);
   }
   public <A> void accept(lang.visitor.GJVoidVisitor<A> v, A argu) {
      choice.accept(v,argu);
   }

   public void accept(lang.visitor.ListVisitor v) {
     choice.accept(v);
   }
   public <R,A> R accept(lang.visitor.GJListVisitor<R,A> v, A argu) {
     return choice.accept(v,argu);
   }
   public <R> R accept(lang.visitor.GJNoArguListVisitor<R> v) {
     return choice.accept(v);
   }
   public <A> void accept(lang.visitor.GJVoidListVisitor<A> v, A argu) {
     choice.accept(v,argu);
   }

   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }

   private Node parent;
   public void setSubNodes(ArrayList<Node> n) { subNodes = n; }
   public ArrayList<Node> getSubNodes() { return subNodes; }
   private ArrayList<Node> subNodes = new ArrayList<Node>();
   public Node choice;
   public int which;
}

