//
// Generated by JTB 1.3.3
//

package lang.minijava.syntaxtree;

/**
 * Grammar production:
 * f0 -> "class"
 * f1 -> Identifier()
 * f2 -> "{"
 * f3 -> "public"
 * f4 -> "static"
 * f5 -> "void"
 * f6 -> "main"
 * f7 -> "("
 * f8 -> "String"
 * f9 -> "["
 * f10 -> "]"
 * f11 -> Identifier()
 * f12 -> ")"
 * f13 -> "{"
 * f14 -> PrintStatement()
 * f15 -> "}"
 * f16 -> "}"
 */
import java.util.*;
import lang.syntaxtree.*;
public class MainClass implements Node {
   private Node parent;
   public NodeToken f0;
   public Identifier f1;
   public NodeToken f2;
   public NodeToken f3;
   public NodeToken f4;
   public NodeToken f5;
   public NodeToken f6;
   public NodeToken f7;
   public NodeToken f8;
   public NodeToken f9;
   public NodeToken f10;
   public Identifier f11;
   public NodeToken f12;
   public NodeToken f13;
   public PrintStatement f14;
   public NodeToken f15;
   public NodeToken f16;
   private ArrayList<Node> subNodes = new ArrayList<Node>();

   public MainClass(NodeToken n0, Identifier n1, NodeToken n2, NodeToken n3, NodeToken n4, NodeToken n5, NodeToken n6, NodeToken n7, NodeToken n8, NodeToken n9, NodeToken n10, Identifier n11, NodeToken n12, NodeToken n13, PrintStatement n14, NodeToken n15, NodeToken n16) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
      f1 = n1;
      if ( f1 != null ) f1.setParent(this);
      f2 = n2;
      if ( f2 != null ) f2.setParent(this);
      f3 = n3;
      if ( f3 != null ) f3.setParent(this);
      f4 = n4;
      if ( f4 != null ) f4.setParent(this);
      f5 = n5;
      if ( f5 != null ) f5.setParent(this);
      f6 = n6;
      if ( f6 != null ) f6.setParent(this);
      f7 = n7;
      if ( f7 != null ) f7.setParent(this);
      f8 = n8;
      if ( f8 != null ) f8.setParent(this);
      f9 = n9;
      if ( f9 != null ) f9.setParent(this);
      f10 = n10;
      if ( f10 != null ) f10.setParent(this);
      f11 = n11;
      if ( f11 != null ) f11.setParent(this);
      f12 = n12;
      if ( f12 != null ) f12.setParent(this);
      f13 = n13;
      if ( f13 != null ) f13.setParent(this);
      f14 = n14;
      if ( f14 != null ) f14.setParent(this);
      f15 = n15;
      if ( f15 != null ) f15.setParent(this);
      f16 = n16;
      if ( f16 != null ) f16.setParent(this);

      buildSubNodesList();
   }

   public MainClass(Identifier n0, Identifier n1, PrintStatement n2) {
      f0 = new NodeToken("class");
      if ( f0 != null ) f0.setParent(this);
      f1 = n0;
      if ( f1 != null ) f1.setParent(this);
      f2 = new NodeToken("{");
      if ( f2 != null ) f2.setParent(this);
      f3 = new NodeToken("public");
      if ( f3 != null ) f3.setParent(this);
      f4 = new NodeToken("static");
      if ( f4 != null ) f4.setParent(this);
      f5 = new NodeToken("void");
      if ( f5 != null ) f5.setParent(this);
      f6 = new NodeToken("main");
      if ( f6 != null ) f6.setParent(this);
      f7 = new NodeToken("(");
      if ( f7 != null ) f7.setParent(this);
      f8 = new NodeToken("String");
      if ( f8 != null ) f8.setParent(this);
      f9 = new NodeToken("[");
      if ( f9 != null ) f9.setParent(this);
      f10 = new NodeToken("]");
      if ( f10 != null ) f10.setParent(this);
      f11 = n1;
      if ( f11 != null ) f11.setParent(this);
      f12 = new NodeToken(")");
      if ( f12 != null ) f12.setParent(this);
      f13 = new NodeToken("{");
      if ( f13 != null ) f13.setParent(this);
      f14 = n2;
      if ( f14 != null ) f14.setParent(this);
      f15 = new NodeToken("}");
      if ( f15 != null ) f15.setParent(this);
      f16 = new NodeToken("}");
      if ( f16 != null ) f16.setParent(this);

      buildSubNodesList();
   }
   private void buildSubNodesList() {
      subNodes.add(f0);
      subNodes.add(f1);
      subNodes.add(f2);
      subNodes.add(f3);
      subNodes.add(f4);
      subNodes.add(f5);
      subNodes.add(f6);
      subNodes.add(f7);
      subNodes.add(f8);
      subNodes.add(f9);
      subNodes.add(f10);
      subNodes.add(f11);
      subNodes.add(f12);
      subNodes.add(f13);
      subNodes.add(f14);
      subNodes.add(f15);
      subNodes.add(f16);
   }


   public void accept(lang.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(lang.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(lang.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(lang.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }

   public void accept(lang.visitor.ListVisitor v) {
      v.visit(this);
   }
   public <R,A> R accept(lang.visitor.GJListVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(lang.visitor.GJNoArguListVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(lang.visitor.GJVoidListVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
   public void setSubNodes(ArrayList<Node> n) { subNodes = n; }
   public ArrayList<Node> getSubNodes() { return subNodes; }
}

